# Generated by Django 5.2.9 on 2025-12-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text='Example: fa-print, fa-book', max_length=50)),
                ('short_description', models.CharField(max_length=200)),
            ],
        ),
    ]
