# Generated by Django 5.2.9 on 2025-12-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_document_order_print_mode_alter_order_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='print_mode',
        ),
        migrations.AlterField(
            model_name='order',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='orders/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
