# Generated by Django 5.2.9 on 2025-12-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='copies',
        ),
        migrations.RemoveField(
            model_name='order',
            name='document',
        ),
        migrations.RemoveField(
            model_name='order',
            name='print_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='side_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
