# Generated by Django 5.2.9 on 2025-12-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_order_print_mode_alter_order_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='custom_color_pages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='print_mode',
            field=models.CharField(default='bw', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='side_type',
            field=models.CharField(default='single', max_length=50),
        ),
    ]
