# Generated by Django 5.2.9 on 2025-12-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_copies_order_custom_color_pages_order_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='custom_color_pages',
        ),
        migrations.AlterField(
            model_name='order',
            name='print_mode',
            field=models.CharField(default='b/w', max_length=100),
        ),
    ]
