# Generated by Django 5.2.9 on 2025-12-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_order_custom_color_pages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Customer Order', 'verbose_name_plural': 'Customer Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='custom_color_pages',
            field=models.CharField(blank=True, help_text='Temporary storage for custom page numbers', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='print_mode',
            field=models.CharField(default='bw', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ready', 'Ready'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
