# Generated by Django 5.2.9 on 2025-12-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_options_order_custom_color_pages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_color_pages',
            field=models.CharField(blank=True, help_text='Stores raw page numbers before formatting into print_mode', max_length=255, null=True),
        ),
    ]
