# Generated by Django 5.2.9 on 2025-12-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fc_user_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_color_pages',
            field=models.CharField(blank=True, help_text='Stores raw page numbers before formatting', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
