# Generated by Django 5.2.9 on 2025-12-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_address_at_order_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_at_order',
        ),
    ]
