# Generated by Django 5.2.9 on 2025-12-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_order_address_at_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='In Progress', max_length=20),
        ),
    ]
