# Generated by Django 5.2.9 on 2025-12-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Ready', 'Ready'), ('Delivered', 'Delivered')], default='In Progress', max_length=20),
        ),
    ]
