# Generated by Django 5.2.9 on 2025-12-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='orders/images/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='orders/documents/'),
        ),
    ]
