# Generated by Django 5.2.9 on 2025-12-25 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_image_upload_alter_order_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('temp_path', models.CharField(blank=True, max_length=500, null=True)),
                ('temp_image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('copies', models.IntegerField(default=1)),
                ('pages', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('print_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('side_type', models.CharField(default='single', max_length=50)),
                ('custom_color_pages', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
