# Generated by Django 5.2.9 on 2025-12-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='theme_color',
            field=models.CharField(default='#2563eb', max_length=7),
        ),
    ]
