# Generated by Django 5.2.9 on 2025-12-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='custom_color_pages',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
