# Generated by Django 5.2.9 on 2025-12-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_order_options_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='TEMP', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
