# Generated by Django 5.2.9 on 2025-12-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_cartitem_options_order_order_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pages',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_source',
            field=models.CharField(choices=[('CART', 'Ordered from Cart Page'), ('SERVICE', 'Ordered from Service Page')], default='SERVICE', help_text='Identifies if the order came from the Cart or directly from a Service page.', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Ready', 'Ready'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
