# Generated by Django 5.2.9 on 2025-12-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_order_pages_alter_order_order_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_source',
            field=models.CharField(choices=[('CART', 'Ordered from Cart Page'), ('SERVICE', 'Ordered from Service Page')], default='SERVICE', max_length=10),
        ),
    ]
