# Generated by Django 5.2.9 on 2025-12-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_order_order_id_alter_order_order_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=30, null=True, unique=True),
        ),
    ]
