# Generated by Django 5.2.9 on 2025-12-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Main Admin'), ('DEALER', 'Dealer Admin')], default='ADMIN', help_text='Determines if the user sees ₹1.50 (Admin) or ₹1.20 (Dealer) pricing.', max_length=10),
        ),
    ]
