# Generated by Django 5.2.9 on 2025-12-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_order_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_price_per_page', models.DecimalField(decimal_places=2, default=1.5, help_text='Price per page for regular users (admin rate)', max_digits=5)),
                ('dealer_price_per_page', models.DecimalField(decimal_places=2, default=1.2, help_text='Price per page for dealer users', max_digits=5)),
                ('spiral_binding_price_admin', models.DecimalField(decimal_places=2, default=20.0, help_text='Spiral binding price for regular users', max_digits=6)),
                ('spiral_binding_price_dealer', models.DecimalField(decimal_places=2, default=15.0, help_text='Spiral binding price for dealers', max_digits=6)),
                ('soft_binding_price_admin', models.DecimalField(decimal_places=2, default=30.0, help_text='Soft binding price for regular users', max_digits=6)),
                ('soft_binding_price_dealer', models.DecimalField(decimal_places=2, default=25.0, help_text='Soft binding price for dealers', max_digits=6)),
                ('custom_1_4_price_admin', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='1/4 Layout Price (Admin)')),
                ('custom_1_4_price_dealer', models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name='1/4 Layout Price (Dealer)')),
                ('custom_1_8_price_admin', models.DecimalField(decimal_places=2, default=4.0, max_digits=5, verbose_name='1/8 Layout Price (Admin)')),
                ('custom_1_8_price_dealer', models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='1/8 Layout Price (Dealer)')),
                ('custom_1_9_price_admin', models.DecimalField(decimal_places=2, default=4.0, max_digits=5, verbose_name='1/9 Layout Price (Admin)')),
                ('custom_1_9_price_dealer', models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='1/9 Layout Price (Dealer)')),
                ('spiral_tier1_limit', models.IntegerField(default=40, help_text='Page limit for Tier 1')),
                ('spiral_tier2_limit', models.IntegerField(default=60, help_text='Page limit for Tier 2')),
                ('spiral_tier3_limit', models.IntegerField(default=90, help_text='Page limit for Tier 3')),
                ('spiral_tier1_price_admin', models.DecimalField(decimal_places=2, default=20.0, max_digits=6, verbose_name='Spiral Tier 1 Price (Admin)')),
                ('spiral_tier1_price_dealer', models.DecimalField(decimal_places=2, default=20.0, max_digits=6, verbose_name='Spiral Tier 1 Price (Dealer)')),
                ('spiral_tier2_price_admin', models.DecimalField(decimal_places=2, default=25.0, max_digits=6, verbose_name='Spiral Tier 2 Price (Admin)')),
                ('spiral_tier2_price_dealer', models.DecimalField(decimal_places=2, default=25.0, max_digits=6, verbose_name='Spiral Tier 2 Price (Dealer)')),
                ('spiral_tier3_price_admin', models.DecimalField(decimal_places=2, default=30.0, max_digits=6, verbose_name='Spiral Tier 3 Price (Admin)')),
                ('spiral_tier3_price_dealer', models.DecimalField(decimal_places=2, default=30.0, max_digits=6, verbose_name='Spiral Tier 3 Price (Dealer)')),
                ('spiral_extra_price_admin', models.DecimalField(decimal_places=2, default=5.0, help_text='Extra cost per 20 pages above Tier 3 (Admin)', max_digits=6)),
                ('spiral_extra_price_dealer', models.DecimalField(decimal_places=2, default=5.0, help_text='Extra cost per 20 pages above Tier 3 (Dealer)', max_digits=6)),
                ('color_price_addition_admin', models.DecimalField(decimal_places=2, default=5.0, help_text='Additional charge per color page for regular users', max_digits=5)),
                ('color_price_addition_dealer', models.DecimalField(decimal_places=2, default=3.0, help_text='Additional charge per color page for dealers', max_digits=5)),
                ('delivery_price_admin', models.DecimalField(decimal_places=2, default=40.0, max_digits=5, verbose_name='Delivery Charge (Admin)')),
                ('delivery_price_dealer', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='Delivery Charge (Dealer)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configuration',
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_dealer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='price_per_page',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dealer_locations',
            field=models.ManyToManyField(blank=True, help_text='Select assigned locations for this dealer.', to='core.location'),
        ),
    ]
