# Generated by Django 5.2.9 on 2025-12-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Main Admin'), ('DEALER', 'Dealer Admin')], default='ADMIN', help_text='Set to DEALER to restrict view and use ₹1.20 pricing logic.', max_length=10),
        ),
    ]
