# Generated by Django 4.2.9 on 2025-12-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_location_pricingconfig_publicholiday_and_more'),
        ('core', '0026_remove_userprofile_role_alter_userprofile_user'),
    ]

    operations = [
    ]
