# Generated by Django 4.2.9 on 2025-12-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_20251229_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfig',
            name='admin_price_per_page_double',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='Price per page for regular users (admin rate) - Double Side', max_digits=5),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='color_price_addition_admin_double',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Additional charge per color page for regular users - Double Side', max_digits=5),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='color_price_addition_dealer_double',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='Additional charge per color page for dealers - Double Side', max_digits=5),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='dealer_price_per_page_double',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Price per page for dealer users - Double Side', max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='admin_price_per_page',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Price per page for regular users (admin rate) - Single Side', max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='color_price_addition_admin',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Additional charge per color page for regular users - Single Side', max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='color_price_addition_dealer',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Additional charge per color page for dealers - Single Side', max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='dealer_price_per_page',
            field=models.DecimalField(decimal_places=2, default=1.2, help_text='Price per page for dealer users - Single Side', max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='delivery_price_admin',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='delivery_price_dealer',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='spiral_extra_price_admin',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='spiral_extra_price_dealer',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='spiral_tier1_limit',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='spiral_tier1_price_admin',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='spiral_tier1_price_dealer',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='spiral_tier2_limit',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='spiral_tier2_price_admin',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='spiral_tier2_price_dealer',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='spiral_tier3_limit',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='spiral_tier3_price_admin',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='spiral_tier3_price_dealer',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=6),
        ),
    ]
