# Generated by Django 4.2.9 on 2025-12-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_pricingconfig_admin_price_per_page_double_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique coupon code (e.g., SAVE20, WELCOME10)', max_length=50, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g., 10.00 for 10% off)', max_digits=5)),
                ('valid_from', models.DateTimeField(help_text='Coupon becomes active from this date/time')),
                ('valid_until', models.DateTimeField(help_text='Coupon expires after this date/time')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order amount required to use this coupon', max_digits=10)),
                ('max_usage_count', models.IntegerField(default=0, help_text='Maximum number of times this coupon can be used (0 = unlimited)')),
                ('current_usage_count', models.IntegerField(default=0, editable=False, help_text='Current number of times this coupon has been used')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this coupon')),
                ('description', models.TextField(blank=True, help_text='Internal description or notes about this coupon', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Applied coupon code', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount from coupon', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount', max_digits=10, null=True),
        ),
    ]
