# Generated by Django 5.2.5 on 2025-12-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_coupon_order_coupon_code_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfig',
            name='custom_1_8_price_double_admin',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='1/8 Layout Price Double (Admin)'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='custom_1_8_price_double_dealer',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=5, verbose_name='1/8 Layout Price Double (Dealer)'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='custom_1_9_price_double_admin',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='1/9 Layout Price Double (Admin)'),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='custom_1_9_price_double_dealer',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=5, verbose_name='1/9 Layout Price Double (Dealer)'),
        ),
    ]
