# Generated by Django 4.2.9 on 2025-12-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_pricingconfig_custom_1_8_price_double_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(help_text='Upload an image for the popup/modal', upload_to='offers/')),
                ('action_url', models.URLField(blank=True, help_text='Optional URL to redirect when clicked', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(help_text='When to start showing this offer')),
                ('end_date', models.DateTimeField(help_text='When to stop showing this offer')),
                ('priority', models.IntegerField(default=1, help_text='Higher number means higher priority if multiple overlap')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
